// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsit7fyLzN5kysYTLtxHdAmQ0N2krKpQA',
    appId: '1:36222842118:web:92b475a6c16ac9c7395a87',
    messagingSenderId: '36222842118',
    projectId: 'therapii-qezlke',
    authDomain: 'therapii-qezlke.firebaseapp.com',
    storageBucket: 'therapii-qezlke.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusVInRfAFteE1uRY7V5VNtfEG4c-wDos',
    appId: '1:36222842118:android:c7ee25da13cbb5bf395a87',
    messagingSenderId: '36222842118',
    projectId: 'therapii-qezlke',
    storageBucket: 'therapii-qezlke.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbiTfr0SCL2vmOvpL128JqCJbNbaG86c',
    appId: '1:36222842118:ios:e6477273c359c09b395a87',
    messagingSenderId: '36222842118',
    projectId: 'therapii-qezlke',
    storageBucket: 'therapii-qezlke.firebasestorage.app',
    androidClientId: '36222842118-7ava3m8bpnalpgb7u2ako3afsvlistfa.apps.googleusercontent.com',
    iosClientId: '36222842118-h3glvtbbc901307bj76m1efqd84rrj8j.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.therapii',
  );

}